package enum

type ANALISIS_STATUS string

const (
	NOT_STARTED                   ANALISIS_STATUS = "NOT_STARTED"
	IN_QUEUE                      ANALISIS_STATUS = "QUEUED"
	VALIDATING_TEMPLATE           ANALISIS_STATUS = "VALIDATING_TEMPLATE"
	EXTRACTING_INFO               ANALISIS_STATUS = "EXTRACTING_INFO"
	EXTRACTING_TRANSACTIONS       ANALISIS_STATUS = "EXTRACTING_TRANSACTIONS"
	ANALYZING                     ANALISIS_STATUS = "ANALYZING"
	COMPLETED                     ANALISIS_STATUS = "COMPLETED"
	FAILED_UPLOAD                 ANALISIS_STATUS = "FAILED_UPLOAD"
	FAILED_TEMPLATE_NOT_FOUND     ANALISIS_STATUS = "FAILED_TEMPLATE_NOT_FOUND"
	FAILED_INFO_EXTRACTION        ANALISIS_STATUS = "FAILED_INFO_EXTRACTION"
	FAILED_TRANSACTION_EXTRACTION ANALISIS_STATUS = "FAILED_TRANSACTION_EXTRACTION"
	FAILED_ANALYSIS               ANALISIS_STATUS = "FAILED_ANALYSIS"
)
